version: "2"
linters:
  enable:
    - loglinter


  settings:
    custom:
      loglinter:
        type: "module"
        description: "Checks logs to be proper"
        settings:
          extra-ban-words: ["private", "ip", "err"]
          disable-flags: [] #"low_first_letter", "english-only", "special-symbols", "sensitive-words"