version: "2"
linters:
  enable:
    - loglinter


  settings:
    custom:
      loglinter:
        type: "module"
        description: "Checks logs to be proper"
        settings:
          extra-ban-words: ["private", "IP"]